# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

first = 1
second = 2

sum = 2 #sum starts from 2 since 2 is the first even term

new_term = 0


while new_term <= 4_000_000
		new_term = first + second   #produces the new term of the sequence, from the 3rd term onwards
		first = second
		second = new_term
		sum += new_term if (new_term % 2 == 0)
end 

puts "\n The sum of the even valued terms of the whose values do not exceed 4 million of the Fibonacci sequence is:  #{sum} "